# Generated by Django 4.2.10 on 2024-03-10 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_user_jwt_alter_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='jwt',
            new_name='token',
        ),
    ]
