version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    # volumes:
    #     - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #     - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  auth:
    build:
      context: auth
    ports:
      - 8000:8000
    restart: always
    command: python /app/manage.py listener
    # command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./auth:/app

  task:
    build:
      context: task
    ports:
      - 8010:8010
    restart: always
    command: python /app/manage.py runserver 0.0.0.0:8010
    volumes:
      - ./task:/app