# Generated by Django 4.2.10 on 2024-03-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_task_assign_value_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assign_value',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена назначения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='done_value',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена выполнения'),
        ),
    ]
